---
- name: creates directory {{ path }}
  file:
    path: "{{ path }}"
    state: directory
    owner: "{{ owner | default(omit) }}"
    group: "{{ group | default(omit) }}"
    mode: "{{ mode | default(700) }}"
  when: path is defined
